# $Id$
#
# Macro file for "Hadr03.cc"
# (can be run in batch, without graphic)
#
/control/verbose 2
/run/verbose 2
#
#/testhadr/det/setIsotopeMat GD156 64 156 10.46 g/cm3
#/testhadr/det/setIsotopeMat Deuterium 1 2 2.02 g/cm3
/testhadr/det/setMat BC537
/testhadr/det/setSize 1 m
#
/run/initialize
#
/gun/particle neutron
#/gun/particle proton
/gun/energy 10 MeV
#
/process/list
/process/inactivate hadElastic
#
/analysis/setFileName neutron_BC537
/analysis/h1/set 2  100  0. 1000 keV	#gamma
/analysis/h1/set 6  100  0. 3000 keV	#alpha
/analysis/h1/set 7  100  0. 2000 keV	#nuclei
#/analysis/h1/set 10 100  0. 3000 keV	#Q
/analysis/h1/set 10 15000  -10. 15. MeV	#Q
/analysis/h1/set 11 100  0.  100 keV	#Pbalance

/analysis/h1/set 13 15000 -10. 15. MeV #Q for deuteron breakup
#
/run/printProgress 100000
#
/run/beamOn 10000000
